# Generated by Django 5.1.3 on 2025-05-27 13:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillathonEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EbekUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(help_text='Required. A valid email address.', max_length=255, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user can log in.')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether this user can access the admin site.')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates whether this user has all permissions without explicitly assigning them.')),
                ('user_role', models.CharField(blank=True, choices=[('super_admin', 'super_admin'), ('ebek_admin', 'ebek_admin'), ('group_admin', 'group_admin'), ('institute_admin', 'institute_admin'), ('hospital_admin', 'hospital_admin'), ('learner', 'learner'), ('supervisor', 'supervisor'), ('skillathon_admin', 'skillathon_admin')], default='', help_text='User Role', max_length=200, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='When the user account was created.')),
                ('last_login', models.DateTimeField(blank=True, help_text='Last login timestamp.', null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='ebek_user_set', related_query_name='ebek_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='ebek_user_set', related_query_name='ebek_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('institution', 'Institution'), ('hospital', 'Hospital')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('group_head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_head_of', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('nurse_strength', models.IntegerField(blank=True, null=True)),
                ('number_of_beds', models.IntegerField(blank=True, null=True)),
                ('hospital_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.group')),
                ('unit_head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_head_of_hospital', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('total_strength', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.group')),
                ('unit_head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_head_of_institution', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessor_type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], max_length=10)),
                ('staff_id', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('qualification', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=100)),
                ('specialization', models.CharField(choices=[('clinical', 'Clinical'), ('academic', 'Academic')], max_length=20)),
                ('assessor_id', models.CharField(max_length=50, unique=True)),
                ('is_verifier', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.hospital')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onboarding_type', models.CharField(choices=[('b2b', 'B2B'), ('b2c', 'B2C')], max_length=3)),
                ('learner_type', models.CharField(choices=[('student', 'Student'), ('nurse', 'Working Nurse')], max_length=10)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('stream', models.CharField(blank=True, choices=[('bsc_4y', 'BSc (4Y)'), ('gnm_3y', 'GNM (3Y Diploma)'), ('post_basic_2y', 'Post-basic (2Y)'), ('msc', 'MSc (Speciality)')], max_length=20, null=True)),
                ('year_of_study', models.IntegerField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('educational_qualification', models.CharField(blank=True, choices=[('bsc_4y', 'BSc (4Y)'), ('gnm_3y', 'GNM (3Y Diploma)'), ('post_basic_2y', 'Post-basic (2Y)'), ('msc', 'MSc (Speciality)')], max_length=20, null=True)),
                ('educational_institution', models.CharField(blank=True, max_length=255, null=True)),
                ('speciality', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('address', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField()),
                ('certifications', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.institution')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.hospital')),
                ('learner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
