# Generated by Django 5.1.3 on 2025-05-26 08:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbekUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(help_text='Required. A valid email address.', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user can log in.')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether this user can access the admin site.')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates whether this user has all permissions without explicitly assigning them.')),
                ('user_role', models.CharField(blank=True, choices=[('super_admin', 'super_admin'), ('ebek_admin', 'ebek_admin'), ('institute_admin', 'institute_admin'), ('hospital_admin', 'hospital_admin'), ('learner', 'learner'), ('supervisor', 'supervisor'), ('skillathon_admin', 'skillathon_admin')], default='', help_text='User Role', max_length=200, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='When the user account was created.')),
                ('last_login', models.DateTimeField(blank=True, help_text='Last login timestamp.', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='ebek_user_set', related_query_name='ebek_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='ebek_user_set', related_query_name='ebek_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
