# Generated by Django 5.1.3 on 2025-05-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='learner_id',
            field=models.CharField(default=1, editable=False, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessor',
            name='assessor_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
