# Generated by Django 5.1.3 on 2024-11-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedexcel',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
