# Generated by Django 5.1.3 on 2024-11-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_uploadedexcel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedexcel',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
    ]
