# Generated by Django 5.1.3 on 2025-05-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_learner_learner_id_alter_assessor_assessor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='pin_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
