# Generated by Django 5.1.3 on 2025-05-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_alter_institution_address_alter_institution_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='onboarding_type',
            field=models.CharField(choices=[('b2b', 'B2B'), ('b2c', 'B2C')], default=None, max_length=3),
            preserve_default=False,
        ),
    ]
