# Generated by Django 5.1.3 on 2024-11-21 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_alter_uploadedexcel_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedExcel',
        ),
    ]
