# Generated by Django 5.1.3 on 2025-05-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_institution_onboarding_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='onboarding_type',
            field=models.CharField(blank=True, choices=[('b2b', 'B2B'), ('b2c', 'B2C')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='onboarding_type',
            field=models.CharField(blank=True, choices=[('b2b', 'B2B'), ('b2c', 'B2C')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='onboarding_type',
            field=models.CharField(blank=True, choices=[('b2b', 'B2B'), ('b2c', 'B2C')], max_length=3, null=True),
        ),
    ]
