# Generated by Django 5.1.3 on 2025-05-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_hospital_onboarding_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='onboarding_type',
            field=models.CharField(choices=[('b2b', 'B2B'), ('b2c', 'B2C')], max_length=3),
        ),
        migrations.AlterField(
            model_name='institution',
            name='onboarding_type',
            field=models.CharField(choices=[('b2b', 'B2B'), ('b2c', 'B2C')], max_length=3),
        ),
        migrations.AlterField(
            model_name='learner',
            name='onboarding_type',
            field=models.CharField(choices=[('b2b', 'B2B'), ('b2c', 'B2C')], max_length=3),
        ),
    ]
