# Generated by Django 5.1.3 on 2025-05-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_alter_hospital_address_alter_hospital_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='learner_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
