# Generated by Django 5.1.3 on 2025-05-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_learner_learner_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
