# Generated by Django 5.1.3 on 2025-05-29 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_alter_learner_date_of_birth_alter_learner_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='skillathon_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.skillathonevent'),
        ),
    ]
