# Generated by Django 5.1.3 on 2025-05-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_learner_skillathon_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessor',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessor',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assessor',
            name='specialization',
            field=models.CharField(blank=True, choices=[('clinical', 'Clinical'), ('academic', 'Academic')], max_length=20, null=True),
        ),
    ]
