# Generated by Django 5.1.3 on 2025-05-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0011_alter_assessor_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebekuser',
            name='user_role',
            field=models.CharField(blank=True, choices=[('super_admin', 'super_admin'), ('ebek_admin', 'ebek_admin'), ('group_admin', 'group_admin'), ('institute_admin', 'institute_admin'), ('hospital_admin', 'hospital_admin'), ('student', 'student'), ('nurse', 'nurse'), ('supervisor', 'supervisor'), ('skillathon_admin', 'skillathon_admin')], default='', help_text='User Role', max_length=200, null=True),
        ),
    ]
