# Generated by Django 5.1.3 on 2025-06-02 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0012_alter_ebekuser_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillathonevent',
            name='status',
        ),
    ]
