# Generated by Django 5.2.3 on 2025-07-29 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0013_remove_skillathonevent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedularObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('data', models.TextField(blank=True, null=True)),
                ('update_data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(default='', max_length=500)),
                ('exam_assignment_id', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.learner')),
            ],
        ),
    ]
