# Generated by Django 5.2.3 on 2025-07-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0014_schedularobject_examassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='examassignment',
            name='type_of_event',
            field=models.CharField(blank=True, choices=[('skillathon', 'Skillathon'), ('mock', 'Mock'), ('classroom', 'Classroom'), ('final', 'Final')], default='', help_text='type_of_event', max_length=200, null=True),
        ),
    ]
