# Generated by Django 5.2.3 on 2025-07-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0015_examassignment_type_of_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='examassignment',
            name='skillathon_name',
            field=models.CharField(blank=True, default='', help_text='skillathon_name', max_length=200, null=True),
        ),
    ]
