from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from .onboarding_views import learner_list, learner_list_api

urlpatterns = [
    path('', views.login_page, name='login_page'),
    path('base/', views.base, name='base'),
    path('create_assessment/', views.create_assessment, name='create_assessment'),
    path('upload_excel/', views.upload_excel_view, name='upload_excel'),
    path('procedures/<str:procedure_id>/<str:action>/', views.ProcedureAPIView.as_view(), name='procedure_api'),
    path('assign_assessment/', views.assign_assessment, name='assign_assessment'),
    path('api/tests/<str:test_id>/delete/', views.delete_test, name='delete_test'),
    path('api/tests/<str:test_id>/update/', views.update_test, name='update_test'),
    path('api/tests/<str:test_id>/', views.get_test, name='get_test'),
    path('course-management/', views.course_management, name='course_management'),
    path('course-management/<str:course_id>/', views.course_detail, name='course_detail'),
    path('batch-management/', views.batch_management, name='batch_management'),
    path('batch-management/<str:batch_id>/', views.batch_detail, name='batch_detail'),
    path('fetch-institutes/', views.fetch_institutes, name='fetch_institutes'),
    path('fetch-cohorts/', views.fetch_cohorts, name='fetch-cohorts'),
    path('fetch-assessors/', views.fetch_assessors, name='fetch-assessors'),
    path('fetch-procedures/', views.fetch_procedures, name='fetch-procedures'),
    path('fetch-course-procedures/<str:course_id>/', views.fetch_course_procedures, name='fetch-course-procedures'),
    path('create-procedure-assignment-and-test/', views.create_procedure_assignment_and_test, name='create-procedure-assignment-and-test'),
    path('exam-reports/', views.render_exam_reports_page, name='exam_reports_page'),
    path('fetch-exam-reports/', views.fetch_exam_reports, name='fetch_exam_reports'),
    path('fetch-exam-metrics/', views.fetch_exam_metrics, name='fetch_exam_metrics'),
    path('fetch-student-metrics/', views.fetch_student_metrics, name='fetch_student_metrics'),
    path('fetch-particular-student/', views.fetch_particular_student, name='fetch_particular_student'),
    path('institutes/', views.institute_list, name='institute_list'),
    path('institutes/create/', views.create_institute, name='create_institute'),
    path('update-test-status/<str:test_id>/<str:status>/', views.update_test_status, name='update_test_status'),
    # path('users/upload-excel/', views.upload_users_excel_view, name='upload_users_excel'),
    # path('users/create/', views.create_user, name='create_user'),
    # path('users/', views.users_management, name='users_management'),
    # path('users/edit/', views.edit_user, name='edit_user'),
    # path('cohorts/', views.cohort_list, name='cohort_list'),
    # path('cohorts/create/', views.create_cohort, name='create_cohort'),
    # path('cohorts/fetch-institute-students/', views.fetch_institute_students, name='fetch_institute_students'),
    # path('cohorts/<str:cohort_id>/add-student/', views.add_student_to_cohort, name='add_student_to_cohort'),
    # path('cohorts/<str:cohort_id>/view-students/', views.view_cohort_students, name='view_cohort_students'),
    # path('cohorts/<str:cohort_id>/get-students/', views.get_cohort_students, name='get_cohort_students'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('reset-password/<uuid:token>/', views.reset_password, name='reset_password'),
    path('onboarding/groups/', views.group_list, name='group_list'),
    path('onboarding/groups/create/', views.group_create, name='group_create'),
    path('onboarding/groups/<int:pk>/edit/', views.group_edit, name='group_edit'),
    path('onboarding/groups/<int:pk>/delete/', views.group_delete, name='group_delete'),
    path('onboarding/', views.onboarding_dashboard, name='onboarding_dashboard'),
    path('onboarding/institutions/', views.institution_list, name='institution_list'),
    path('onboarding/institutions/api/', views.institution_list_api, name='institution_list_api'),
    path('onboarding/institutions/create/', views.institution_create, name='institution_create'),
    path('onboarding/institutions/<int:pk>/edit/', views.institution_edit, name='institution_edit'),
    path('onboarding/institutions/<int:pk>/delete/', views.institution_delete, name='institution_delete'),
    path('onboarding/hospitals/', views.hospital_list, name='hospital_list'),
    path('onboarding/hospitals/create/', views.hospital_create, name='hospital_create'),
    path('onboarding/hospitals/<int:pk>/edit/', views.hospital_edit, name='hospital_edit'),
    path('onboarding/hospitals/<int:pk>/delete/', views.hospital_delete, name='hospital_delete'),
    path('onboarding/learners/', learner_list, name='learner_list'),
    path('onboarding/learners/api/', learner_list_api, name='learner_list_api'),
    path('onboarding/learners/create/', views.learner_create, name='learner_create'),
    path('onboarding/learners/<int:pk>/edit/', views.learner_edit, name='learner_edit'),
    path('onboarding/learners/<int:pk>/delete/', views.learner_delete, name='learner_delete'),
    path('onboarding/learners/bulk-upload/', views.learner_bulk_upload, name='learner_bulk_upload'),
    path('onboarding/learners/upload-progress/<str:session_key>/', views.upload_progress_stream, name='upload_progress_stream'),
    path('onboarding/assessors/', views.assessor_list, name='assessor_list'),
    path('onboarding/assessors/create/', views.assessor_create, name='assessor_create'),
    path('onboarding/assessors/<int:pk>/edit/', views.assessor_edit, name='assessor_edit'),
    path('onboarding/assessors/<int:pk>/delete/', views.assessor_delete, name='assessor_delete'),
    path('onboarding/skillathon/', views.skillathon_list, name='skillathon_list'),
    path('onboarding/skillathon/create/', views.skillathon_create, name='skillathon_create'),
    path('onboarding/skillathon/<int:pk>/edit/', views.skillathon_edit, name='skillathon_edit'),
    path('onboarding/skillathon/<int:pk>/delete/', views.skillathon_delete, name='skillathon_delete'),
    path('fetch-skillathons/', views.fetch_skillathons, name='fetch_skillathons'),
    path('create-course/', views.create_course, name='create_course'),
    path('fetch-courses/', views.fetch_courses, name='fetch_courses'),
    path('courses/<str:course_id>/delete/', views.delete_course, name='delete_course'),
    path('courses/<str:course_id>/toggle-status/', views.toggle_course_status, name='toggle_course_status'),
    path('courses/<str:course_id>/update/', views.update_course, name='update_course'),
    path('courses/<str:course_id>/add-procedures/', views.add_procedures_to_course, name='add_procedures_to_course'),
    path('courses/<str:course_id>/remove-procedure/', views.remove_procedure_from_course, name='remove_procedure_from_course'),
    path('create-roles/', views.create_roles, name='create_roles'),
    path('assign-roles/', views.assign_roles, name='assign_roles'),
    
    # Batch API endpoints
    path('api/batches/', views.fetch_batches, name='fetch_batches'),
    path('api/batches/create/', views.create_batch, name='create_batch'),
    path('api/batches/<str:batch_id>/', views.fetch_batch_details, name='fetch_batch_details'),
    path('api/batches/<str:batch_id>/update/', views.update_batch, name='update_batch'),
    path('api/batches/<str:batch_id>/delete/', views.delete_batch, name='delete_batch'),
    path('api/batches/<str:batch_id>/remove-learners/', views.remove_learners_from_batch, name='remove_learners_from_batch'),
    path('api/batches/<str:batch_id>/add-learners/', views.add_learners_to_batch, name='add_learners_to_batch'),
    path('api/batches/<str:batch_id>/available-learners/', views.fetch_available_learners_for_batch, name='fetch_available_learners_for_batch'),
    path('api/fetch-hospitals/', views.fetch_hospitals, name='fetch_hospitals'),
    path('api/fetch-learners/<str:unit_type>/<str:unit_id>/', views.fetch_learners, name='fetch_learners'),
    path('api/institute-based-skillathon/', views.institute_based_skillathon, name='institute_based_skillathon'),
    path('api/download-student-report/', views.download_student_report, name='download_student_report'),


    # Batch Course API endpoints
    path('api/batches/<str:batch_id>/courses/', views.fetch_batch_courses, name='fetch_batch_courses'),
    path('api/batches/<str:batch_id>/courses-paginated/', views.fetch_batch_courses_paginated, name='fetch_batch_courses_paginated'),
    path('api/batches/<str:batch_id>/learners/', views.fetch_batch_learners, name='fetch_batch_learners'),
    path('api/batches/<str:batch_id>/add-courses/', views.add_courses_to_batch, name='add_courses_to_batch'),
    path('api/batches/<str:batch_id>/remove-courses/', views.remove_courses_from_batch, name='remove_courses_from_batch'),
    path('api/batches/<str:batch_id>/available-courses/', views.fetch_available_courses_for_batch, name='fetch_available_courses_for_batch'),
    path('courses/<str:course_id>/batches/', views.fetch_batches_for_course, name='fetch_batches_for_course'),
    path('onboarding/hospitals/api/', views.hospital_list_api, name='hospital_list_api'),
    path('onboarding/groups/api/', views.group_list_api, name='group_list_api'),
    path('onboarding/assessors/api/', views.assessor_list_api, name='assessor_list_api'),
    path('onboarding/assessors/get-institutions-hospitals/', views.get_institutions_hospitals, name='get_institutions_hospitals'),
    path('onboarding/skillathons/api/', views.skillathon_list_api, name='skillathon_list_api'),
    path('onboarding/sync-strength-counts/', views.sync_strength_counts, name='sync_strength_counts'),
    path('api/roles/', views.get_roles, name='get_roles'),
    path('api/roles/<int:role_id>/edit/', views.edit_role, name='edit_role'),
    path('api/roles/<int:role_id>/delete/', views.delete_role, name='delete_role'),
    path('api/users/create/', views.create_user, name='create_user'),
    path('api/users/<int:user_id>/update/', views.update_user, name='update_user'),
    path('api/users/<int:user_id>/', views.get_user, name='get_user'),
    path('api/users/<int:user_id>/delete/', views.delete_user, name='delete_user'),
    path('api/users/<int:user_id>/toggle-active/', views.toggle_user_active, name='toggle_user_active'),
    path('onboarding/learners/get-institutions-by-skillathon/', views.get_institutions_by_skillathon, name='get_institutions_by_skillathon'),
    path('onboarding/learners/get-hospitals-by-skillathon/', views.get_hospitals_by_skillathon, name='get_hospitals_by_skillathon'),
]
