#!/usr/bin/env python3
"""
Accurate Functional Test Cases for EBEK OSCE Platform
Created by analyzing actual codebase at /Users/sanujphilip/Desktop/Ebek/
Based on real features and endpoints found in the code
"""

# Functional test cases based on ACTUAL EBEK codebase
# Categories: Authentication, Onboarding, Exam Management, Reports, Admin

functional_test_cases = [
    # ===== AUTHENTICATION TESTS (10 cases: FUNC-001 to FUNC-010) =====
    # Based on: views.py login_page(), login_view(), logout_view(), forgot_password(), reset_password()

    {"id": "FUNC-001", "category": "Authentication", "priority": "P0",
     "test_name": "Login with valid credentials",
     "description": "User can login with correct email and password",
     "preconditions": "User account exists, user is active (is_active=True)",
     "steps": "1. Navigate to /login/\n2. Enter valid email\n3. Enter valid password\n4. Click login button\n5. Verify redirected to dashboard",
     "test_data": "email: test@example.com, password: Test@1234",
     "expected": "User logged in, session created, redirected to /base/ or dashboard",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:login_view()"},

    {"id": "FUNC-002", "category": "Authentication", "priority": "P0",
     "test_name": "Login with invalid email",
     "description": "Login fails with non-existent email",
     "preconditions": "User doesn't exist",
     "steps": "1. Go to /login/\n2. Enter non-existent email\n3. Enter any password\n4. Click login",
     "test_data": "email: notexist@example.com",
     "expected": "Login fails, error message shown, user stays on login page",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:login_view()"},

    {"id": "FUNC-003", "category": "Authentication", "priority": "P0",
     "test_name": "Login with wrong password",
     "description": "Login fails with incorrect password",
     "preconditions": "User exists with known password",
     "steps": "1. Go to /login/\n2. Enter correct email\n3. Enter wrong password\n4. Click login",
     "test_data": "email: test@example.com, password: WrongPass@123",
     "expected": "Login fails, error message shown",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:login_view()"},

    {"id": "FUNC-004", "category": "Authentication", "priority": "P0",
     "test_name": "Login with inactive user",
     "description": "Inactive user cannot login",
     "preconditions": "User exists but is_active=False",
     "steps": "1. Go to /login/\n2. Enter inactive user credentials\n3. Try login",
     "test_data": "user with is_active=False",
     "expected": "Login fails, account disabled message shown",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:login_view()"},

    {"id": "FUNC-005", "category": "Authentication", "priority": "P0",
     "test_name": "Logout",
     "description": "User can logout and session destroyed",
     "preconditions": "User logged in",
     "steps": "1. Login user\n2. Click logout\n3. Try access protected page",
     "test_data": "logged in user",
     "expected": "Session destroyed, redirected to login page for protected access",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:logout_view()"},

    {"id": "FUNC-006", "category": "Authentication", "priority": "P0",
     "test_name": "Forgot password - Request",
     "description": "User can request password reset",
     "preconditions": "User exists with valid email",
     "steps": "1. Go to /forgot-password/\n2. Enter email\n3. Click 'Send Reset Link'\n4. Check email for reset link",
     "test_data": "email: test@example.com",
     "expected": "Password reset email sent with valid reset link",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:forgot_password()"},

    {"id": "FUNC-007", "category": "Authentication", "priority": "P0",
     "test_name": "Password reset - Valid token",
     "description": "User can reset password with valid token",
     "preconditions": "Valid password reset token received",
     "steps": "1. Click reset link from email\n2. Enter new password\n3. Confirm password\n4. Click reset\n5. Login with new password",
     "test_data": "new password: NewPass@456",
     "expected": "Password changed, login succeeds with new password",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:reset_password()"},

    {"id": "FUNC-008", "category": "Authentication", "priority": "P1",
     "test_name": "Password reset - Expired token",
     "description": "Expired reset token rejected (>10 minutes)",
     "preconditions": "Reset token older than 10 minutes",
     "steps": "1. Wait 10+ minutes after token generation\n2. Click reset link\n3. Try reset password",
     "test_data": "expired token",
     "expected": "Token expired error, redirect to forgot password",
     "actual": "", "status": "Not Run", "file": "assessments/models.py:PasswordResetToken.is_valid()"},

    {"id": "FUNC-009", "category": "Authentication", "priority": "P1",
     "test_name": "Password reset - Already used token",
     "description": "Used password reset token cannot be reused",
     "preconditions": "Password already reset with this token",
     "steps": "1. Reset password with token\n2. Try use same token again\n3. Check error",
     "test_data": "used token",
     "expected": "Token already used error, cannot reset again",
     "actual": "", "status": "Not Run", "file": "assessments/models.py:PasswordResetToken.is_used"},

    {"id": "FUNC-010", "category": "Authentication", "priority": "P1",
     "test_name": "Inactive user auto-logout",
     "description": "Inactive user logged out on next request",
     "preconditions": "User logged in and active",
     "steps": "1. Login user\n2. Set is_active=False in database\n3. Make request from logged-in user",
     "test_data": "user toggled to inactive",
     "expected": "User auto-logged out, redirected to login, session destroyed",
     "actual": "", "status": "Not Run", "file": "assessments/middleware.py:CheckInactiveUserMiddleware"},

    # ===== GROUP ONBOARDING (5 cases: FUNC-011 to FUNC-015) =====
    # Based on: onboarding_views.py - group_list(), group_create(), group_edit(), group_delete()

    {"id": "FUNC-011", "category": "Group Management", "priority": "P1",
     "test_name": "View group list",
     "description": "Admin can view list of groups",
     "preconditions": "Admin logged in, groups exist",
     "steps": "1. Navigate to /onboarding/groups/\n2. Check list of groups displayed",
     "test_data": "groups exist in database",
     "expected": "List of groups shown with name, type, head, group_id",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:group_list()"},

    {"id": "FUNC-012", "category": "Group Management", "priority": "P1",
     "test_name": "Create group",
     "description": "Admin can create new group",
     "preconditions": "Admin logged in, has create permission",
     "steps": "1. Go to /onboarding/groups/create/\n2. Enter group name\n3. Select type (institution/hospital)\n4. Click create",
     "test_data": "name: Medical Group, type: institution",
     "expected": "Group created, appears in list, group_id auto-generated",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:group_create()"},

    {"id": "FUNC-013", "category": "Group Management", "priority": "P1",
     "test_name": "Edit group",
     "description": "Admin can edit group details",
     "preconditions": "Group exists",
     "steps": "1. Navigate to /onboarding/groups/<id>/edit/\n2. Change name\n3. Save",
     "test_data": "name: Medical Group -> Metro Medical Group",
     "expected": "Group updated, changes saved",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:group_edit()"},

    {"id": "FUNC-014", "category": "Group Management", "priority": "P1",
     "test_name": "Delete group",
     "description": "Admin can delete empty group",
     "preconditions": "Group exists with no institutions/hospitals",
     "steps": "1. Navigate to /onboarding/groups/<id>/delete/\n2. Confirm deletion",
     "test_data": "empty group",
     "expected": "Group deleted, removed from list",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:group_delete()"},

    {"id": "FUNC-015", "category": "Group Management", "priority": "P2",
     "test_name": "Group API - Assign head",
     "description": "Assign group_head sets user_role to group_admin",
     "preconditions": "Group and user exist",
     "steps": "1. Edit group\n2. Assign group_head\n3. Check user's role changed to group_admin",
     "test_data": "user becomes group_head",
     "expected": "User role automatically set to 'group_admin'",
     "actual": "", "status": "Not Run", "file": "assessments/models.py:Group.save()"},

    # ===== INSTITUTION MANAGEMENT (10 cases: FUNC-016 to FUNC-025) =====
    # Based on: onboarding_views.py - institution_list(), institution_create(), institution_edit(), etc.

    {"id": "FUNC-016", "category": "Institution Management", "priority": "P1",
     "test_name": "View institution list",
     "description": "Admin can view institutions",
     "preconditions": "Admin logged in",
     "steps": "1. Navigate to /onboarding/institutions/\n2. Check institutions displayed",
     "test_data": "institutions exist",
     "expected": "List shows: name, group, unit_head, total_strength, institute_id",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:institution_list()"},

    {"id": "FUNC-017", "category": "Institution Management", "priority": "P0",
     "test_name": "Create institution",
     "description": "Admin can create new institution",
     "preconditions": "Admin logged in, group exists",
     "steps": "1. Go to /onboarding/institutions/create/\n2. Enter name, select group\n3. Enter total_strength\n4. Click create",
     "test_data": "name: DJ Sanghvi College, group: Medical, strength: 100",
     "expected": "Institution created, institute_id auto-generated, synced to Firebase",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:institution_create()"},

    {"id": "FUNC-018", "category": "Institution Management", "priority": "P1",
     "test_name": "Edit institution",
     "description": "Admin can edit institution details",
     "preconditions": "Institution exists",
     "steps": "1. Navigate to /onboarding/institutions/<id>/edit/\n2. Change name or strength\n3. Save",
     "test_data": "strength: 100 -> 120",
     "expected": "Institution updated, Firebase synced",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:institution_edit()"},

    {"id": "FUNC-019", "category": "Institution Management", "priority": "P0",
     "test_name": "Delete institution",
     "description": "Delete institution without learners",
     "preconditions": "Institution exists, no linked learners",
     "steps": "1. Navigate to /onboarding/institutions/<id>/delete/\n2. Confirm deletion",
     "test_data": "empty institution",
     "expected": "Institution deleted, removed from list",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:institution_delete()"},

    {"id": "FUNC-020", "category": "Institution Management", "priority": "P1",
     "test_name": "Cannot delete institution with learners",
     "description": "Cannot delete institution with linked learners",
     "preconditions": "Institution has learners",
     "steps": "1. Try delete institution\n2. Check error message",
     "test_data": "institution: DJ Sanghvi (has learners)",
     "expected": "Error: Cannot delete institution with linked learners",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:institution_delete()"},

    {"id": "FUNC-021", "category": "Institution Management", "priority": "P1",
     "test_name": "Assign unit head to institution",
     "description": "Assigning unit_head makes user institute_admin",
     "preconditions": "Institution and user exist",
     "steps": "1. Edit institution\n2. Assign unit_head\n3. Check user's role is now institute_admin",
     "test_data": "user becomes unit_head",
     "expected": "User role automatically set to 'institute_admin'",
     "actual": "", "status": "Not Run", "file": "assessments/models.py:Institution.save()"},

    {"id": "FUNC-022", "category": "Institution Management", "priority": "P1",
     "test_name": "Toggle institution active status",
     "description": "Admin can activate/deactivate institution",
     "preconditions": "Institution exists",
     "steps": "1. Navigate to institution\n2. Toggle active status\n3. Verify inactive institution hidden from lists",
     "test_data": "status: active -> inactive",
     "expected": "Institution status toggled, Firebase updated, filtering applies",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:institution_toggle_status()"},

    {"id": "FUNC-023", "category": "Institution Management", "priority": "P1",
     "test_name": "Institution list filtered by assignment",
     "description": "Non-admin user sees only assigned institutions",
     "preconditions": "Inst admin assigned to specific institutions",
     "steps": "1. Login as inst admin\n2. Go to /onboarding/institutions/\n3. Verify only assigned institutions shown",
     "test_data": "assigned_institutions: [DJ Sanghvi, SVKM]",
     "expected": "Only assigned institutions visible",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:institution_list()"},

    {"id": "FUNC-024", "category": "Institution Management", "priority": "P2",
     "test_name": "Super admin sees all institutions",
     "description": "Super admin can see all institutions",
     "preconditions": "Super admin logged in",
     "steps": "1. Login as super admin\n2. Go to institutions list\n3. Verify all institutions shown",
     "test_data": "user_role: super_admin",
     "expected": "All institutions visible regardless of assignment",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:institution_list()"},

    {"id": "FUNC-025", "category": "Institution Management", "priority": "P1",
     "test_name": "Institution API endpoint",
     "description": "API endpoint returns institutions list",
     "preconditions": "Institutions exist",
     "steps": "1. GET /onboarding/institutions/\n2. Check JSON response",
     "test_data": "API call",
     "expected": "JSON array of institutions with all fields",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:institution_list_api()"},

    # ===== HOSPITAL MANAGEMENT (5 cases: FUNC-026 to FUNC-030) =====
    # Based on: onboarding_views.py - hospital_list(), hospital_create(), etc.

    {"id": "FUNC-026", "category": "Hospital Management", "priority": "P1",
     "test_name": "Create hospital",
     "description": "Admin can create hospital",
     "preconditions": "Admin logged in, group exists",
     "steps": "1. Go to /onboarding/hospitals/create/\n2. Enter name, group, beds, nurse_strength\n3. Click create",
     "test_data": "name: Apollo Hospital, beds: 500, nurse_strength: 200",
     "expected": "Hospital created, hospital_id auto-generated",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:hospital_create()"},

    {"id": "FUNC-027", "category": "Hospital Management", "priority": "P1",
     "test_name": "Edit hospital",
     "description": "Admin can edit hospital",
     "preconditions": "Hospital exists",
     "steps": "1. Go to hospital edit page\n2. Change details\n3. Save",
     "test_data": "nurse_strength: 200 -> 250",
     "expected": "Hospital updated",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:hospital_edit()"},

    {"id": "FUNC-028", "category": "Hospital Management", "priority": "P1",
     "test_name": "Delete hospital",
     "description": "Admin can delete empty hospital",
     "preconditions": "Hospital exists, no learners",
     "steps": "1. Navigate to delete hospital\n2. Confirm",
     "test_data": "empty hospital",
     "expected": "Hospital deleted",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:hospital_delete()"},

    {"id": "FUNC-029", "category": "Hospital Management", "priority": "P1",
     "test_name": "Toggle hospital active status",
     "description": "Admin can activate/deactivate hospital",
     "preconditions": "Hospital exists",
     "steps": "1. Toggle hospital status\n2. Verify inactive hospital hidden",
     "test_data": "status: active -> inactive",
     "expected": "Hospital status toggled",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:hospital_toggle_status()"},

    {"id": "FUNC-030", "category": "Hospital Management", "priority": "P1",
     "test_name": "Hospital API endpoint",
     "description": "API returns hospitals list",
     "preconditions": "Hospitals exist",
     "steps": "1. GET /onboarding/hospitals/\n2. Check JSON response",
     "test_data": "API call",
     "expected": "JSON array of hospitals",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:hospital_list_api()"},

    # ===== LEARNER MANAGEMENT (15 cases: FUNC-031 to FUNC-045) =====
    # Based on: onboarding_views.py - learner_list(), learner_create(), learner_bulk_upload(), etc.

    {"id": "FUNC-031", "category": "Learner Management", "priority": "P1",
     "test_name": "Create student learner",
     "description": "Admin can create student learner",
     "preconditions": "Admin logged in, institution exists",
     "steps": "1. Go to /onboarding/learners/create/\n2. Select learner_type: student\n3. Enter name, select college\n4. Click create",
     "test_data": "name: John Doe, college: DJ Sanghvi, type: student",
     "expected": "Learner created, learner_id auto-generated, user account created, Firebase synced",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:learner_create()"},

    {"id": "FUNC-032", "category": "Learner Management", "priority": "P1",
     "test_name": "Create nurse learner",
     "description": "Admin can create nurse learner",
     "preconditions": "Admin logged in, hospital exists",
     "steps": "1. Go to /onboarding/learners/create/\n2. Select learner_type: nurse\n3. Enter name, select hospital\n4. Click create",
     "test_data": "name: Jane Doe, hospital: Apollo, type: nurse",
     "expected": "Nurse learner created, associated with hospital",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:learner_create()"},

    {"id": "FUNC-033", "category": "Learner Management", "priority": "P0",
     "test_name": "Bulk upload learners via Excel",
     "description": "Admin can bulk upload learners from Excel file",
     "preconditions": "Admin logged in, Excel file prepared with learner data",
     "steps": "1. Go to /onboarding/learners/bulk-upload/\n2. Select Excel file\n3. Preview data\n4. Click upload\n5. Wait for processing\n6. Verify learners created",
     "test_data": "Excel file with 50 learner records (name, email, roll_number, etc.)",
     "expected": "All 50 learners created, progress tracked, Firebase synced",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:learner_bulk_upload()"},

    {"id": "FUNC-034", "category": "Learner Management", "priority": "P1",
     "test_name": "Bulk upload - CSV validation",
     "description": "Bulk upload validates Excel format",
     "preconditions": "Invalid Excel file prepared",
     "steps": "1. Try upload invalid file\n2. Check error message",
     "test_data": "Excel with missing required columns",
     "expected": "Validation error shown, learners not created",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:learner_bulk_upload()"},

    {"id": "FUNC-035", "category": "Learner Management", "priority": "P1",
     "test_name": "View learner list",
     "description": "Admin can view learners list",
     "preconditions": "Admin logged in",
     "steps": "1. Navigate to /onboarding/learners/\n2. Check list displayed",
     "test_data": "learners exist",
     "expected": "List shows: name, email, college/hospital, learner_id, type",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:learner_list()"},

    {"id": "FUNC-036", "category": "Learner Management", "priority": "P1",
     "test_name": "Edit learner",
     "description": "Admin can edit learner details",
     "preconditions": "Learner exists",
     "steps": "1. Navigate to /onboarding/learners/<id>/edit/\n2. Change details\n3. Save",
     "test_data": "email: john@example.com -> john.doe@example.com",
     "expected": "Learner updated, Firebase synced",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:learner_edit()"},

    {"id": "FUNC-037", "category": "Learner Management", "priority": "P1",
     "test_name": "Delete learner",
     "description": "Admin can delete learner",
     "preconditions": "Learner exists",
     "steps": "1. Navigate to /onboarding/learners/<id>/delete/\n2. Confirm",
     "test_data": "learner to delete",
     "expected": "Learner soft-deleted (is_active=False), Firebase updated",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:learner_delete()"},

    {"id": "FUNC-038", "category": "Learner Management", "priority": "P1",
     "test_name": "Toggle learner active status",
     "description": "Admin can activate/deactivate learner",
     "preconditions": "Learner exists",
     "steps": "1. Toggle learner status\n2. Try login as inactive learner",
     "test_data": "status: active -> inactive",
     "expected": "Inactive learner cannot login",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:learner_toggle_status()"},

    {"id": "FUNC-039", "category": "Learner Management", "priority": "P2",
     "test_name": "Learner list filtered by assignment",
     "description": "Institution admin sees only assigned institution learners",
     "preconditions": "Inst admin assigned to one institution",
     "steps": "1. Login as inst admin\n2. Go to /onboarding/learners/\n3. Check only assigned institution learners shown",
     "test_data": "inst admin assigned to DJ Sanghvi",
     "expected": "Only DJ Sanghvi learners visible",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:learner_list()"},

    {"id": "FUNC-040", "category": "Learner Management", "priority": "P1",
     "test_name": "Bulk delete learners",
     "description": "Admin can bulk delete multiple learners",
     "preconditions": "Multiple learners exist",
     "steps": "1. Select multiple learners\n2. Click bulk delete\n3. Confirm",
     "test_data": "10 learners selected",
     "expected": "All selected learners deleted",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:learners_bulk_delete()"},

    {"id": "FUNC-041", "category": "Learner Management", "priority": "P1",
     "test_name": "Check bulk upload progress",
     "description": "Admin can check upload progress",
     "preconditions": "Bulk upload in progress",
     "steps": "1. Start bulk upload\n2. Check progress endpoint: /api/status-update/<task_id>/\n3. Monitor completion",
     "test_data": "uploading 100 learners",
     "expected": "Progress tracked and displayed in real-time",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:check_status_update_progress()"},

    {"id": "FUNC-042", "category": "Learner Management", "priority": "P1",
     "test_name": "Learner can login and view results",
     "description": "Created learner can login and access exam results",
     "preconditions": "Learner created with account",
     "steps": "1. Login as learner\n2. Navigate to results page\n3. Check results visible",
     "test_data": "learner account",
     "expected": "Learner sees their exam results",
     "actual": "", "status": "Not Run", "file": "assessments/views.py"},

    {"id": "FUNC-043", "category": "Learner Management", "priority": "P1",
     "test_name": "Learner API endpoint",
     "description": "API returns learners list",
     "preconditions": "Learners exist",
     "steps": "1. GET /onboarding/learners/\n2. Check JSON response",
     "test_data": "API call",
     "expected": "JSON array of learners",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:learner_list_api()"},

    {"id": "FUNC-044", "category": "Learner Management", "priority": "P2",
     "test_name": "Learner gender tracked",
     "description": "Learner gender (learner_gender) saved and used for analytics",
     "preconditions": "Learner created with gender",
     "steps": "1. Create learner with gender field\n2. View analytics\n3. Check gender breakdown",
     "test_data": "gender: Male, Female, Other",
     "expected": "Gender data persisted, used in gender metrics",
     "actual": "", "status": "Not Run", "file": "assessments/models.py:Learner.learner_gender"},

    {"id": "FUNC-045", "category": "Learner Management", "priority": "P2",
     "test_name": "Sync learner strength counts",
     "description": "Learner count synced to Firebase",
     "preconditions": "Learners created/updated",
     "steps": "1. Create/delete learners\n2. Call /api/sync-strength-counts/\n3. Check Firebase updated",
     "test_data": "learner count changes",
     "expected": "Learner counts synced to Firebase institutions collection",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:sync_strength_counts()"},

    # ===== ASSESSOR MANAGEMENT (8 cases: FUNC-046 to FUNC-053) =====
    # Based on: onboarding_views.py - assessor_list(), assessor_create(), etc.

    {"id": "FUNC-046", "category": "Assessor Management", "priority": "P1",
     "test_name": "Create internal assessor",
     "description": "Admin can create internal assessor",
     "preconditions": "Admin logged in, institution exists",
     "steps": "1. Go to /onboarding/assessors/create/\n2. Select type: internal\n3. Enter name, select institution\n4. Click create",
     "test_data": "name: Dr. Smith, institution: DJ Sanghvi, type: internal",
     "expected": "Internal assessor created, assessor_id auto-generated, user_role set to ebek_admin",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:assessor_create()"},

    {"id": "FUNC-047", "category": "Assessor Management", "priority": "P1",
     "test_name": "Create external assessor",
     "description": "Admin can create external assessor",
     "preconditions": "Admin logged in",
     "steps": "1. Go to /onboarding/assessors/create/\n2. Select type: external\n3. Enter name, email\n4. Click create",
     "test_data": "name: Prof. Jones, email: jones@external.com, type: external",
     "expected": "External assessor created, user_role set to supervisor",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:assessor_create()"},

    {"id": "FUNC-048", "category": "Assessor Management", "priority": "P1",
     "test_name": "View assessor list",
     "description": "Admin can view assessors",
     "preconditions": "Admin logged in",
     "steps": "1. Navigate to /onboarding/assessors/\n2. Check list",
     "test_data": "assessors exist",
     "expected": "List shows: name, type, institution, assessor_id",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:assessor_list()"},

    {"id": "FUNC-049", "category": "Assessor Management", "priority": "P1",
     "test_name": "Edit assessor",
     "description": "Admin can edit assessor details",
     "preconditions": "Assessor exists",
     "steps": "1. Navigate to edit page\n2. Change details\n3. Save",
     "test_data": "assessor details",
     "expected": "Assessor updated",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:assessor_edit()"},

    {"id": "FUNC-050", "category": "Assessor Management", "priority": "P1",
     "test_name": "Delete assessor",
     "description": "Admin can delete assessor",
     "preconditions": "Assessor exists",
     "steps": "1. Navigate to delete\n2. Confirm",
     "test_data": "assessor to delete",
     "expected": "Assessor soft-deleted",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:assessor_delete()"},

    {"id": "FUNC-051", "category": "Assessor Management", "priority": "P1",
     "test_name": "Toggle assessor active status",
     "description": "Admin can activate/deactivate assessor",
     "preconditions": "Assessor exists",
     "steps": "1. Toggle status\n2. Try login as inactive assessor",
     "test_data": "status: active -> inactive",
     "expected": "Inactive assessor cannot login",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:assessor_toggle_status() if exists"},

    {"id": "FUNC-052", "category": "Assessor Management", "priority": "P1",
     "test_name": "Assessor login and view assigned exams",
     "description": "Assessor can login and see assigned exams",
     "preconditions": "Assessor created, exams assigned",
     "steps": "1. Login as assessor\n2. Navigate to assessments\n3. Check assigned exams shown",
     "test_data": "assessor account",
     "expected": "Assessor sees only assigned exams",
     "actual": "", "status": "Not Run", "file": "assessments/views.py"},

    {"id": "FUNC-053", "category": "Assessor Management", "priority": "P1",
     "test_name": "Assessor API endpoint",
     "description": "API returns assessors list",
     "preconditions": "Assessors exist",
     "steps": "1. GET /onboarding/assessors/\n2. Check JSON",
     "test_data": "API call",
     "expected": "JSON array of assessors",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:assessor_list_api()"},

    # ===== COURSE & BATCH MANAGEMENT (20 cases: FUNC-054 to FUNC-073) =====
    # Based on: views.py - course_management(), batch_management(), etc.

    {"id": "FUNC-054", "category": "Course Management", "priority": "P1",
     "test_name": "View courses",
     "description": "Admin can view list of courses",
     "preconditions": "Admin logged in, courses exist",
     "steps": "1. Navigate to /course-management/\n2. Check courses displayed",
     "test_data": "courses exist",
     "expected": "List of courses shown",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:course_management()"},

    {"id": "FUNC-055", "category": "Course Management", "priority": "P0",
     "test_name": "Create course",
     "description": "Admin can create course",
     "preconditions": "Admin logged in",
     "steps": "1. Navigate to create course page\n2. Enter course name\n3. Add procedures to course\n4. Save",
     "test_data": "name: OSCE Year 2, procedures: Suturing, Injection, etc.",
     "expected": "Course created with procedures",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:create_course()"},

    {"id": "FUNC-056", "category": "Course Management", "priority": "P1",
     "test_name": "Edit course",
     "description": "Admin can edit course",
     "preconditions": "Course exists",
     "steps": "1. Navigate to edit page\n2. Change course name\n3. Save",
     "test_data": "course name",
     "expected": "Course updated",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:update_course()"},

    {"id": "FUNC-057", "category": "Course Management", "priority": "P0",
     "test_name": "Delete course",
     "description": "Admin can delete course",
     "preconditions": "Course exists, no batches assigned",
     "steps": "1. Navigate to delete\n2. Confirm",
     "test_data": "course to delete",
     "expected": "Course deleted",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:delete_course()"},

    {"id": "FUNC-058", "category": "Course Management", "priority": "P1",
     "test_name": "Toggle course active status",
     "description": "Admin can activate/deactivate course",
     "preconditions": "Course exists",
     "steps": "1. Toggle course status\n2. Check inactive course not available for batch assignment",
     "test_data": "status: active -> inactive",
     "expected": "Course status toggled, filtering applies",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:toggle_course_status()"},

    {"id": "FUNC-059", "category": "Course Management", "priority": "P1",
     "test_name": "Add procedures to course",
     "description": "Admin can add procedures to course",
     "preconditions": "Course and procedures exist",
     "steps": "1. Navigate to course edit\n2. Add procedure\n3. Save",
     "test_data": "procedure: Suturing",
     "expected": "Procedure added to course",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:add_procedures_to_course()"},

    {"id": "FUNC-060", "category": "Course Management", "priority": "P1",
     "test_name": "Remove procedure from course",
     "description": "Admin can remove procedure from course",
     "preconditions": "Course has procedures",
     "steps": "1. Navigate to course\n2. Remove procedure\n3. Confirm",
     "test_data": "procedure to remove",
     "expected": "Procedure removed from course",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:remove_procedure_from_course()"},

    {"id": "FUNC-061", "category": "Batch Management", "priority": "P1",
     "test_name": "View batches",
     "description": "Admin can view batches",
     "preconditions": "Admin logged in, batches exist",
     "steps": "1. Navigate to /batch-management/\n2. Check batches displayed",
     "test_data": "batches exist",
     "expected": "List of batches shown",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:batch_management()"},

    {"id": "FUNC-062", "category": "Batch Management", "priority": "P0",
     "test_name": "Create batch",
     "description": "Admin can create batch",
     "preconditions": "Admin logged in",
     "steps": "1. Navigate to create batch\n2. Enter batch name\n3. Select courses to assign\n4. Save",
     "test_data": "name: Batch A 2025, courses: [OSCE Year 2]",
     "expected": "Batch created with courses assigned",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:create_batch() if exists"},

    {"id": "FUNC-063", "category": "Batch Management", "priority": "P1",
     "test_name": "Add learners to batch",
     "description": "Admin can add learners to batch",
     "preconditions": "Batch and learners exist",
     "steps": "1. Navigate to batch detail\n2. Add learners\n3. Save",
     "test_data": "batch: Batch A, learners: [John, Jane, ...]",
     "expected": "Learners added to batch",
     "actual": "", "status": "Not Run", "file": "assessments/views.py"},

    {"id": "FUNC-064", "category": "Batch Management", "priority": "P1",
     "test_name": "Remove learners from batch",
     "description": "Admin can remove learners from batch",
     "preconditions": "Batch has learners",
     "steps": "1. Navigate to batch\n2. Remove learner\n3. Confirm",
     "test_data": "learner to remove",
     "expected": "Learner removed from batch",
     "actual": "", "status": "Not Run", "file": "assessments/views.py"},

    {"id": "FUNC-065", "category": "Batch Management", "priority": "P1",
     "test_name": "Add courses to batch",
     "description": "Admin can add courses to batch",
     "preconditions": "Batch and courses exist",
     "steps": "1. Navigate to batch\n2. Add course\n3. Save",
     "test_data": "course: OSCE Year 2",
     "expected": "Course added to batch",
     "actual": "", "status": "Not Run", "file": "assessments/views.py"},

    {"id": "FUNC-066", "category": "Batch Management", "priority": "P1",
     "test_name": "Remove courses from batch",
     "description": "Admin can remove courses from batch",
     "preconditions": "Batch has courses",
     "steps": "1. Navigate to batch\n2. Remove course\n3. Confirm",
     "test_data": "course to remove",
     "expected": "Course removed from batch",
     "actual": "", "status": "Not Run", "file": "assessments/views.py"},

    {"id": "FUNC-067", "category": "Batch Management", "priority": "P1",
     "test_name": "Toggle batch active status",
     "description": "Admin can activate/deactivate batch",
     "preconditions": "Batch exists",
     "steps": "1. Toggle batch status\n2. Check inactive batch not available",
     "test_data": "status: active -> inactive",
     "expected": "Batch status toggled",
     "actual": "", "status": "Not Run", "file": "assessments/views.py"},

    {"id": "FUNC-068", "category": "Batch Management", "priority": "P1",
     "test_name": "View batch learners API",
     "description": "API returns batch learners",
     "preconditions": "Batch with learners exists",
     "steps": "1. GET /api/batches/<id>/learners/\n2. Check JSON",
     "test_data": "API call",
     "expected": "JSON array of learners in batch",
     "actual": "", "status": "Not Run", "file": "assessments/views.py"},

    {"id": "FUNC-069", "category": "Batch Management", "priority": "P1",
     "test_name": "View batch courses API",
     "description": "API returns batch courses",
     "preconditions": "Batch with courses exists",
     "steps": "1. GET /api/batches/<id>/courses/\n2. Check JSON",
     "test_data": "API call",
     "expected": "JSON array of courses in batch",
     "actual": "", "status": "Not Run", "file": "assessments/views.py"},

    {"id": "FUNC-070", "category": "Batch Management", "priority": "P1",
     "test_name": "Batch detail page",
     "description": "Admin can view batch details",
     "preconditions": "Batch exists",
     "steps": "1. Navigate to /batch-management/<id>/\n2. Check batch details, learners, courses shown",
     "test_data": "batch: Batch A",
     "expected": "Batch detail page shows all information",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:batch_detail()"},

    {"id": "FUNC-071", "category": "Batch Management", "priority": "P1",
     "test_name": "Delete batch",
     "description": "Admin can delete batch",
     "preconditions": "Batch exists",
     "steps": "1. Navigate to delete batch\n2. Confirm",
     "test_data": "batch to delete",
     "expected": "Batch deleted",
     "actual": "", "status": "Not Run", "file": "assessments/views.py"},

    {"id": "FUNC-072", "category": "Batch Management", "priority": "P1",
     "test_name": "Update batch summary",
     "description": "Admin can update batch assignment summary",
     "preconditions": "Batch exists",
     "steps": "1. Navigate to batch\n2. Update summary details\n3. Save",
     "test_data": "batch summary data",
     "expected": "Summary updated",
     "actual": "", "status": "Not Run", "file": "assessments/views.py"},

    {"id": "FUNC-073", "category": "Batch Management", "priority": "P1",
     "test_name": "View available learners for batch",
     "description": "API returns learners available to add to batch",
     "preconditions": "Batch exists",
     "steps": "1. GET /api/batches/<id>/available-learners/\n2. Check JSON",
     "test_data": "API call",
     "expected": "JSON array of available learners",
     "actual": "", "status": "Not Run", "file": "assessments/views.py"},

    # ===== EXAM ASSIGNMENT & MANAGEMENT (15 cases: FUNC-074 to FUNC-088) =====
    # Based on: views.py - create_assessment(), assign_assessment(), fetch procedures, etc.

    {"id": "FUNC-074", "category": "Exam Management", "priority": "P0",
     "test_name": "Create exam assignment",
     "description": "Admin can create exam (procedure assignments)",
     "preconditions": "Admin logged in, batch and course exist",
     "steps": "1. Navigate to /create_assessment/\n2. Select batch, course, assessors\n3. Click create",
     "test_data": "batch: Batch A, course: OSCE Year 2, type: final",
     "expected": "Exam created, test record in Firebase, assessors assigned to procedures",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:create_assessment()"},

    {"id": "FUNC-075", "category": "Exam Management", "priority": "P1",
     "test_name": "Fetch institutions for exam",
     "description": "Admin can fetch institutions list for exam creation",
     "preconditions": "Institutions exist",
     "steps": "1. GET /fetch-institutes/\n2. Check JSON response",
     "test_data": "API call",
     "expected": "JSON array of institutions",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:fetch_institutes()"},

    {"id": "FUNC-076", "category": "Exam Management", "priority": "P1",
     "test_name": "Fetch batches for exam",
     "description": "Admin can fetch batches list",
     "preconditions": "Batches exist",
     "steps": "1. GET /fetch-cohorts/\n2. Check JSON response",
     "test_data": "API call",
     "expected": "JSON array of batches",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:fetch_cohorts()"},

    {"id": "FUNC-077", "category": "Exam Management", "priority": "P1",
     "test_name": "Fetch assessors for exam",
     "description": "Admin can fetch assessors list",
     "preconditions": "Assessors exist",
     "steps": "1. GET /fetch-assessors/\n2. Check JSON response",
     "test_data": "API call",
     "expected": "JSON array of assessors",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:fetch_assessors()"},

    {"id": "FUNC-078", "category": "Exam Management", "priority": "P1",
     "test_name": "Fetch procedures for course",
     "description": "Admin can fetch procedures for selected course",
     "preconditions": "Course with procedures exists",
     "steps": "1. GET /fetch-course-procedures/<course_id>/\n2. Check JSON response",
     "test_data": "API call",
     "expected": "JSON array of course procedures",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:fetch_course_procedures()"},

    {"id": "FUNC-079", "category": "Exam Management", "priority": "P1",
     "test_name": "Assign procedures to learners",
     "description": "Admin can assign procedures to learners in batch",
     "preconditions": "Exam created, learners in batch",
     "steps": "1. Navigate to /assign_assessment/\n2. Select learners, procedures\n3. Click assign",
     "test_data": "batch: Batch A, procedures: [Suturing, Injection, ...]",
     "expected": "ExamAssignment records created in Django and Firebase",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:assign_assessment()"},

    {"id": "FUNC-080", "category": "Exam Management", "priority": "P0",
     "test_name": "View exam details",
     "description": "Admin/assessor can view exam details",
     "preconditions": "Exam exists",
     "steps": "1. GET /api/tests/<test_id>/\n2. Check JSON response",
     "test_data": "test_id",
     "expected": "JSON with exam details, procedures, learners",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:get_test()"},

    {"id": "FUNC-081", "category": "Exam Management", "priority": "P1",
     "test_name": "Update exam status",
     "description": "Admin can update exam status",
     "preconditions": "Exam exists",
     "steps": "1. POST /update-test-status/<test_id>/<status>/\n2. Check status updated",
     "test_data": "status: pending -> in_progress -> completed",
     "expected": "Exam status updated in Django and Firebase",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:update_test_status()"},

    {"id": "FUNC-082", "category": "Exam Management", "priority": "P1",
     "test_name": "Delete exam",
     "description": "Admin can delete exam",
     "preconditions": "Exam exists",
     "steps": "1. DELETE /api/tests/<test_id>/delete/\n2. Check deleted",
     "test_data": "test_id",
     "expected": "Exam deleted from Django and Firebase",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:delete_test()"},

    {"id": "FUNC-083", "category": "Exam Management", "priority": "P1",
     "test_name": "Delete batch assignment",
     "description": "Admin can delete batch assignment",
     "preconditions": "Batch assignment exists",
     "steps": "1. DELETE /api/batch-assignments/<ba_id>/delete/\n2. Check deleted",
     "test_data": "batch_assignment_id",
     "expected": "Assignment deleted",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:delete_batch_assignment()"},

    {"id": "FUNC-084", "category": "Exam Management", "priority": "P1",
     "test_name": "Learner can view assigned exam",
     "description": "Learner can view exam assigned to them",
     "preconditions": "Learner logged in, exam assigned",
     "steps": "1. Login as learner\n2. Navigate to exams\n3. Check assigned exam visible",
     "test_data": "learner account",
     "expected": "Learner sees assigned exams",
     "actual": "", "status": "Not Run", "file": "assessments/views.py"},

    {"id": "FUNC-085", "category": "Exam Management", "priority": "P1",
     "test_name": "Learner can start exam",
     "description": "Learner can start and work on exam",
     "preconditions": "Exam assigned to learner",
     "steps": "1. Login as learner\n2. Click start exam\n3. Check exam interface loads",
     "test_data": "assigned exam",
     "expected": "Exam interface loads with procedures",
     "actual": "", "status": "Not Run", "file": "Firebase Firestore (frontend logic)"},

    {"id": "FUNC-086", "category": "Exam Management", "priority": "P1",
     "test_name": "Exam type tracking",
     "description": "Exam type (mock/final/classroom/skillathon) tracked correctly",
     "preconditions": "Exam created with specific type",
     "steps": "1. Create exam with type: mock\n2. View exam details\n3. Check type persisted",
     "test_data": "type_of_event: mock",
     "expected": "Exam type correctly stored and retrieved",
     "actual": "", "status": "Not Run", "file": "assessments/models.py:ExamAssignment.type_of_event"},

    {"id": "FUNC-087", "category": "Exam Management", "priority": "P1",
     "test_name": "Skillathon exam assignment",
     "description": "Learners can be assigned to skillathon exams",
     "preconditions": "Skillathon event and learners exist",
     "steps": "1. Create exam with skillathon type\n2. Assign learners\n3. Check assigned",
     "test_data": "type_of_event: skillathon",
     "expected": "Skillathon assignment created",
     "actual": "", "status": "Not Run", "file": "assessments/models.py:ExamAssignment.skillathon_name"},

    {"id": "FUNC-088", "category": "Exam Management", "priority": "P1",
     "test_name": "Assessor can access Firebase exam data",
     "description": "Assessor can view exam data from Firebase",
     "preconditions": "Assessor logged in, exam assigned",
     "steps": "1. Login as assessor\n2. Access exam\n3. Check learner procedures visible",
     "test_data": "assessor account",
     "expected": "Assessor sees exam details from Firebase",
     "actual": "", "status": "Not Run", "file": "Firebase Firestore (frontend)"},

    # ===== REPORTS & ANALYTICS (18 cases: FUNC-089 to FUNC-106) =====
    # Based on: views.py - render_exam_reports_page(), fetch_exam_reports(), etc.

    {"id": "FUNC-089", "category": "Reports & Analytics", "priority": "P1",
     "test_name": "View exam reports page",
     "description": "Admin can view exam reports dashboard",
     "preconditions": "Admin logged in",
     "steps": "1. Navigate to /exam-reports/\n2. Check page loaded",
     "test_data": "exam data exists",
     "expected": "Exam reports page loads with filters and data",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:render_exam_reports_page()"},

    {"id": "FUNC-090", "category": "Reports & Analytics", "priority": "P0",
     "test_name": "Fetch OSCE report (optimized)",
     "description": "Fetch pre-computed OSCE report (fast lookup)",
     "preconditions": "Admin logged in, exam data exists",
     "steps": "1. GET /api/osce-report/?institution_name=DJ%20Sanghvi&academic_year=2025&semester=1\n2. Check response time < 1 second",
     "test_data": "institution: DJ Sanghvi, year: 2025, semester: 1",
     "expected": "Pre-computed report returned in < 1 second (from SemesterMetrics)",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:fetch_osce_report_optimized()"},

    {"id": "FUNC-091", "category": "Reports & Analytics", "priority": "P1",
     "test_name": "Fetch exam metrics",
     "description": "Admin can fetch exam-level metrics",
     "preconditions": "Exam data exists",
     "steps": "1. GET /fetch-exam-metrics/\n2. Check JSON response",
     "test_data": "API call",
     "expected": "JSON with exam metrics (scores, pass rates, etc.)",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:fetch_exam_metrics()"},

    {"id": "FUNC-092", "category": "Reports & Analytics", "priority": "P1",
     "test_name": "Fetch student metrics",
     "description": "Admin can fetch student-level metrics",
     "preconditions": "Student exam data exists",
     "steps": "1. GET /fetch-student-metrics/\n2. Check JSON response",
     "test_data": "API call",
     "expected": "JSON with student metrics (scores, pass/fail, gender, etc.)",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:fetch_student_metrics()"},

    {"id": "FUNC-093", "category": "Reports & Analytics", "priority": "P1",
     "test_name": "Fetch particular student report",
     "description": "Admin can fetch single student report",
     "preconditions": "Student exists with exam data",
     "steps": "1. GET /fetch-particular-student/?student_id=<id>\n2. Check response",
     "test_data": "student_id",
     "expected": "JSON with student's all exam data and performance",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:fetch_particular_student()"},

    {"id": "FUNC-094", "category": "Reports & Analytics", "priority": "P1",
     "test_name": "View metrics viewer",
     "description": "Admin can view analytics metrics viewer",
     "preconditions": "Admin logged in",
     "steps": "1. Navigate to /metrics-viewer/\n2. Check metrics displayed",
     "test_data": "metrics data",
     "expected": "Metrics dashboard loads with analytics data",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:render_metrics_viewer() if exists"},

    {"id": "FUNC-095", "category": "Reports & Analytics", "priority": "P1",
     "test_name": "Gender analytics report",
     "description": "Admin can view gender-based performance analytics",
     "preconditions": "Student data with gender exists",
     "steps": "1. Generate gender analytics report\n2. Check gender breakdown (M/F/Other)",
     "test_data": "student gender data",
     "expected": "Report shows performance by gender using total marks method (student-level aggregation)",
     "actual": "", "status": "Not Run", "file": "assessments/management/commands/process_metric_queue.py (gender_metrics)"},

    {"id": "FUNC-096", "category": "Reports & Analytics", "priority": "P1",
     "test_name": "Download student report",
     "description": "Admin can download student report as PDF or Excel",
     "preconditions": "Student exists with exam data",
     "steps": "1. GET /api/download-student-report/?student_id=<id>&format=pdf\n2. Check file downloaded",
     "test_data": "student_id, format: pdf/excel",
     "expected": "PDF or Excel report downloaded with all student data",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:download_student_report()"},

    {"id": "FUNC-097", "category": "Reports & Analytics", "priority": "P1",
     "test_name": "Download metrics report",
     "description": "Admin can download metrics report",
     "preconditions": "Metrics data exists",
     "steps": "1. GET /api/download-metrics-report/?institution=DJ%20Sanghvi\n2. Check file downloaded",
     "test_data": "institution_name",
     "expected": "Metrics report downloaded",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:download_metrics_report()"},

    {"id": "FUNC-098", "category": "Reports & Analytics", "priority": "P1",
     "test_name": "Semester metrics debug endpoint",
     "description": "Admin can view pre-computed semester metrics (DEBUG)",
     "preconditions": "Metrics computed",
     "steps": "1. GET /api/semester-metrics/?unit_name=DJ%20Sanghvi&year=2025&semester=1\n2. Check JSON",
     "test_data": "API call",
     "expected": "JSON with semester metrics from SemesterMetrics collection",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:fetch_semester_metrics()"},

    {"id": "FUNC-099", "category": "Reports & Analytics", "priority": "P1",
     "test_name": "Unit metrics debug endpoint",
     "description": "Admin can view pre-computed unit metrics (DEBUG)",
     "preconditions": "Metrics computed",
     "steps": "1. GET /api/unit-metrics/?unit_name=DJ%20Sanghvi&year=2025\n2. Check JSON",
     "test_data": "API call",
     "expected": "JSON with unit metrics from UnitMetrics collection",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:fetch_unit_metrics()"},

    {"id": "FUNC-100", "category": "Reports & Analytics", "priority": "P1",
     "test_name": "Admin report portal - Filter options",
     "description": "Admin can fetch filter options for reports",
     "preconditions": "Admin logged in",
     "steps": "1. GET /api/institutions-hospitals-for-report/\n2. Check JSON options",
     "test_data": "API call",
     "expected": "JSON with institutions and hospitals for filtering",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:fetch_institutions_hospitals_for_report()"},

    {"id": "FUNC-101", "category": "Reports & Analytics", "priority": "P1",
     "test_name": "Admin report portal page",
     "description": "Admin can access admin report portal dashboard",
     "preconditions": "Admin logged in",
     "steps": "1. Navigate to /admin-report-portal/\n2. Check dashboard loaded",
     "test_data": "admin data",
     "expected": "Admin report portal loads with filters",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:render_admin_report_portal()"},

    {"id": "FUNC-102", "category": "Reports & Analytics", "priority": "P2",
     "test_name": "Calculate exam score",
     "description": "Exam score calculated correctly",
     "preconditions": "Exam completed, scores entered",
     "steps": "1. Complete exam with scores\n2. Fetch results\n3. Check score calculation",
     "test_data": "procedures: [18/20, 17/20, 19/20]",
     "expected": "Total score and percentage calculated correctly",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:calculate_exam_score()"},

    {"id": "FUNC-103", "category": "Reports & Analytics", "priority": "P1",
     "test_name": "Student can view own results",
     "description": "Student can view their exam results",
     "preconditions": "Student logged in, exam completed",
     "steps": "1. Login as student\n2. Navigate to results\n3. Check results visible",
     "test_data": "student account",
     "expected": "Student sees their exam scores and feedback",
     "actual": "", "status": "Not Run", "file": "assessments/views.py"},

    {"id": "FUNC-104", "category": "Reports & Analytics", "priority": "P2",
     "test_name": "Performance metrics aggregation",
     "description": "Metrics aggregated and pre-computed correctly",
     "preconditions": "Multiple exams completed",
     "steps": "1. Complete multiple exams\n2. Run process_metric_queue command\n3. Verify SemesterMetrics created",
     "test_data": "batch with 50 students",
     "expected": "SemesterMetrics and UnitMetrics created in Firebase with aggregated data",
     "actual": "", "status": "Not Run", "file": "assessments/management/commands/process_metric_queue.py"},

    {"id": "FUNC-105", "category": "Reports & Analytics", "priority": "P2",
     "test_name": "Skills metrics by category",
     "description": "Admin can fetch metrics by skill/procedure category",
     "preconditions": "Skill category data exists",
     "steps": "1. GET /api/skills-for-category/?category=Surgical\n2. Check JSON",
     "test_data": "category: Surgical",
     "expected": "JSON with skills/procedures in category",
     "actual": "", "status": "Not Run", "file": "assessments/views.py"},

    {"id": "FUNC-106", "category": "Reports & Analytics", "priority": "P1",
     "test_name": "Assessor performance metrics",
     "description": "Admin can view assessor performance statistics",
     "preconditions": "Assessor data with evaluations exists",
     "steps": "1. View admin reports\n2. Check assessor performance stats",
     "test_data": "assessor: Dr. Smith",
     "expected": "Shows assessor evaluation count, average scores, consistency metrics",
     "actual": "", "status": "Not Run", "file": "assessments/management/commands/process_metric_queue.py"},

    # ===== SKILLATHON & ADDITIONAL FEATURES (10 cases: FUNC-107 to FUNC-116) =====
    # Based on: onboarding_views.py and views.py

    {"id": "FUNC-107", "category": "Skillathon Management", "priority": "P2",
     "test_name": "Create skillathon event",
     "description": "Admin can create skillathon event",
     "preconditions": "Admin logged in",
     "steps": "1. Navigate to /onboarding/skillathons/create/\n2. Enter event details\n3. Click create",
     "test_data": "name: Tech Summit 2025, date: 2025-05-20, state: CA, city: San Francisco",
     "expected": "Skillathon event created",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:skillathon_create()"},

    {"id": "FUNC-108", "category": "Skillathon Management", "priority": "P2",
     "test_name": "View skillathon events",
     "description": "Admin can view skillathon events",
     "preconditions": "Skillathon events exist",
     "steps": "1. Navigate to /onboarding/skillathons/\n2. Check events displayed",
     "test_data": "skillathon events",
     "expected": "List of skillathon events shown",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:skillathon_list()"},

    {"id": "FUNC-109", "category": "Skillathon Management", "priority": "P2",
     "test_name": "Link institution to skillathon",
     "description": "Institution linked to skillathon event",
     "preconditions": "Institution and skillathon exist",
     "steps": "1. Edit institution\n2. Assign to skillathon\n3. Save",
     "test_data": "institution: DJ Sanghvi, skillathon: Tech Summit 2025",
     "expected": "Institution linked to skillathon",
     "actual": "", "status": "Not Run", "file": "assessments/models.py:Institution.skillathon"},

    {"id": "FUNC-110", "category": "Skillathon Management", "priority": "P2",
     "test_name": "Fetch institutions by skillathon",
     "description": "Admin can fetch institutions for skillathon",
     "preconditions": "Institutions linked to skillathon",
     "steps": "1. GET /api/get-institutions-by-skillathon/?skillathon_id=<id>\n2. Check JSON",
     "test_data": "skillathon_id",
     "expected": "JSON array of institutions linked to skillathon",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:get_institutions_by_skillathon()"},

    {"id": "FUNC-111", "category": "Skillathon Management", "priority": "P2",
     "test_name": "Fetch hospitals by skillathon",
     "description": "Admin can fetch hospitals for skillathon",
     "preconditions": "Hospitals linked to skillathon",
     "steps": "1. GET /api/get-hospitals-by-skillathon/?skillathon_id=<id>\n2. Check JSON",
     "test_data": "skillathon_id",
     "expected": "JSON array of hospitals linked to skillathon",
     "actual": "", "status": "Not Run", "file": "onboarding_views.py:get_hospitals_by_skillathon()"},

    {"id": "FUNC-112", "category": "Skillathon Management", "priority": "P2",
     "test_name": "Learner assigned to skillathon",
     "description": "Learner can be assigned to skillathon event",
     "preconditions": "Learner and skillathon exist",
     "steps": "1. Create/edit learner\n2. Assign to skillathon\n3. Save",
     "test_data": "learner: John Doe, skillathon: Tech Summit 2025",
     "expected": "Learner linked to skillathon event",
     "actual": "", "status": "Not Run", "file": "assessments/models.py:Learner.skillathon_event"},

    {"id": "FUNC-113", "category": "Role Management", "priority": "P1",
     "test_name": "Create custom role",
     "description": "Admin can create custom role with permissions",
     "preconditions": "Admin logged in",
     "steps": "1. Navigate to /create-roles/\n2. Enter role name\n3. Select permissions\n4. Click create",
     "test_data": "role: Editor, permissions: [create_institute, edit_institute, view_reports]",
     "expected": "Custom role created with selected permissions",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:create_roles()"},

    {"id": "FUNC-114", "category": "Role Management", "priority": "P1",
     "test_name": "View roles",
     "description": "Admin can view all roles",
     "preconditions": "Admin logged in, roles exist",
     "steps": "1. GET /api/roles/\n2. Check JSON response",
     "test_data": "API call",
     "expected": "JSON array of all roles with permissions",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:get_roles()"},

    {"id": "FUNC-115", "category": "Role Management", "priority": "P1",
     "test_name": "Edit role",
     "description": "Admin can edit role permissions",
     "preconditions": "Custom role exists",
     "steps": "1. POST /api/roles/<id>/edit/\n2. Update permissions\n3. Save",
     "test_data": "role: Editor, add permission: delete_institute",
     "expected": "Role permissions updated",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:edit_role()"},

    {"id": "FUNC-116", "category": "Role Management", "priority": "P1",
     "test_name": "Delete role",
     "description": "Admin can delete custom role",
     "preconditions": "Custom role exists, not assigned to users",
     "steps": "1. DELETE /api/roles/<id>/delete/\n2. Confirm",
     "test_data": "role_id",
     "expected": "Custom role deleted",
     "actual": "", "status": "Not Run", "file": "assessments/views.py:delete_role()"},
]

# Summary
print(f"✅ Total Functional Test Cases: {len(functional_test_cases)}")
print(f"📊 By Category:")
categories = {}
for tc in functional_test_cases:
    cat = tc['category']
    categories[cat] = categories.get(cat, 0) + 1

for cat in sorted(categories.keys()):
    print(f"   {cat}: {categories[cat]} tests")

priorities = {}
for tc in functional_test_cases:
    p = tc['priority']
    priorities[p] = priorities.get(p, 0) + 1

print(f"\n📈 By Priority:")
for p in sorted(priorities.keys()):
    print(f"   {p}: {priorities[p]} tests")
